config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root 'home#index'
  resources :problema_negativados
  resources :problema_voos
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/problema_negativado.rb
class ProblemaNegativado < ApplicationRecord
end

app/models/problema_voo.rb
class ProblemaVoo < ApplicationRecord
    validates :situacao, :detalhe, :usuario, presence: true 
    validates :usuario, length: {minimum:3, maximum:100}
    validates :detalhe, length: {minimum:3, maximum:250}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/problema_negativados_controller.rb
class ProblemaNegativadosController < ApplicationController
  before_action :set_problema_negativado, only: %i[ show edit update destroy ]

  # GET /problema_negativados or /problema_negativados.json
  def index
    @problema_negativados = ProblemaNegativado.all
  end

  # GET /problema_negativados/1 or /problema_negativados/1.json
  def show
  end

  # GET /problema_negativados/new
  def new
    @problema_negativado = ProblemaNegativado.new
  end

  # GET /problema_negativados/1/edit
  def edit
  end

  # POST /problema_negativados or /problema_negativados.json
  def create
    @problema_negativado = ProblemaNegativado.new(problema_negativado_params)

    respond_to do |format|
      if @problema_negativado.save
        format.html { redirect_to problema_negativado_url(@problema_negativado), notice: "Problema negativado was successfully created." }
        format.json { render :show, status: :created, location: @problema_negativado }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @problema_negativado.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /problema_negativados/1 or /problema_negativados/1.json
  def update
    respond_to do |format|
      if @problema_negativado.update(problema_negativado_params)
        format.html { redirect_to problema_negativado_url(@problema_negativado), notice: "Problema negativado was successfully updated." }
        format.json { render :show, status: :ok, location: @problema_negativado }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @problema_negativado.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /problema_negativados/1 or /problema_negativados/1.json
  def destroy
    @problema_negativado.destroy

    respond_to do |format|
      format.html { redirect_to problema_negativados_url, notice: "Problema negativado was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_problema_negativado
      @problema_negativado = ProblemaNegativado.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def problema_negativado_params
      params.require(:problema_negativado).permit(:divida, :categoria, :usuario, :endereco, :provas, :advogado)
    end
end

app/controllers/problema_voos_controller.rb
class ProblemaVoosController < ApplicationController
  before_action :set_problema_voo, only: %i[ show edit update destroy ]

  # GET /problema_voos or /problema_voos.json
  def index
    @problema_voos = ProblemaVoo.all
  end

  # GET /problema_voos/1 or /problema_voos/1.json
  def show
  end

  # GET /problema_voos/new
  def new
    @problema_voo = ProblemaVoo.new
  end

  # GET /problema_voos/1/edit
  def edit
  end

  # POST /problema_voos or /problema_voos.json
  def create
    @problema_voo = ProblemaVoo.new(problema_voo_params)

    respond_to do |format|
      if @problema_voo.save
        format.html { redirect_to problema_voo_url(@problema_voo), notice: "Problema voo was successfully created." }
        format.json { render :show, status: :created, location: @problema_voo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @problema_voo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /problema_voos/1 or /problema_voos/1.json
  def update
    respond_to do |format|
      if @problema_voo.update(problema_voo_params)
        format.html { redirect_to problema_voo_url(@problema_voo), notice: "Problema voo was successfully updated." }
        format.json { render :show, status: :ok, location: @problema_voo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @problema_voo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /problema_voos/1 or /problema_voos/1.json
  def destroy
    @problema_voo.destroy

    respond_to do |format|
      format.html { redirect_to problema_voos_url, notice: "Problema voo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_problema_voo
      @problema_voo = ProblemaVoo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def problema_voo_params
      params.require(:problema_voo).permit(:situacao, :detalhe, :usuario, :endereço, :provas, :advogado)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/problema_negativados_helper.rb
module ProblemaNegativadosHelper
end

app/helpers/problema_voos_helper.rb
module ProblemaVoosHelper
end

app/views/home/index.html.erb
<h1>Seja bem-vindo(a) a Resolvvi</h1>
<p>Escolha qual o tipo de problema que voce quer relatar?</p>

<%= link_to "Problema com voo", new_problema_voo_path %><br><br>
<%= link_to "Problema com nome negativado indevidamente", new_problema_negativado_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Resolvvi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/problema_negativados/_form.html.erb
<%= form_with(model: problema_negativado) do |form| %>
  <% if problema_negativado.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(problema_negativado.errors.count, "error") %> prohibited this problema_negativado from being saved:</h2>

      <ul>
        <% problema_negativado.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :divida, style: "display: block" %>
    <%= form.text_field :divida %>
  </div>

  <div>
    <%= form.label :categoria, style: "display: block" %>
    <%= form.text_field :categoria %>
  </div>

  <div>
    <%= form.label :usuario, style: "display: block" %>
    <%= form.text_field :usuario %>
  </div>

  <div>
    <%= form.label :endereco, style: "display: block" %>
    <%= form.text_field :endereco %>
  </div>

  <div>
    <%= form.label :provas, style: "display: block" %>
    <%= form.text_field :provas %>
  </div>

  <div>
    <%= form.label :advogado, style: "display: block" %>
    <%= form.text_field :advogado %>
  </div>
<br>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/problema_negativados/_problema_negativado.html.erb
<div id="<%= dom_id problema_negativado %>">
  <p>
    <strong>Divida:</strong>
    <%= problema_negativado.divida %>
  </p>

  <p>
    <strong>Categoria:</strong>
    <%= problema_negativado.categoria %>
  </p>

  <p>
    <strong>Usuario:</strong>
    <%= problema_negativado.usuario %>
  </p>

  <p>
    <strong>Endereco:</strong>
    <%= problema_negativado.endereco %>
  </p>

  <p>
    <strong>Provas:</strong>
    <%= problema_negativado.provas %>
  </p>

  <p>
    <strong>Advogado:</strong>
    <%= problema_negativado.advogado %>
  </p>

</div>

app/views/problema_negativados/edit.html.erb
<h1>Editing problema negativado</h1>

<%= render "form", problema_negativado: @problema_negativado %>

<br>

<div>
  <%= link_to "Visualizar", @problema_negativado %> |
  <%= link_to "Voltar para os problemas com negativados", problema_negativados_path %>
</div>

app/views/problema_negativados/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Problema negativados</h1>

<div id="problema_negativados">
  <% @problema_negativados.each do |problema_negativado| %>
    <%= render problema_negativado %>
    <p>
      <%= link_to "Visualizar", problema_negativado %>
    </p>
  <% end %>
</div>

<%= link_to "Adicionar nova ocorrência", new_problema_negativado_path %><br><br>
<%= link_to "Voltar", root_path %>

app/views/problema_negativados/new.html.erb
<h1>Cadastro de pedidos (negativados)</h1>

<%= render "form", problema_negativado: @problema_negativado %>

<br>

<div>
  <%= link_to "Ir para os problemas com negativados", problema_negativados_path %><br><br>
  <%= link_to "Voltar para o menu", root_path %>
</div>

app/views/problema_negativados/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @problema_negativado %>

<div>
  <%= link_to "Editar", edit_problema_negativado_path(@problema_negativado) %> |
  <%= link_to "Voltar para os problemas com voos", problema_negativados_path %>
<br><br>
  <%= button_to "Apagar", @problema_negativado, method: :delete %><br><br>
  <%= link_to "Voltar para o menu", root_path %>
</div>

app/views/problema_voos/_form.html.erb
<%= form_with(model: problema_voo) do |form| %>
  <% if problema_voo.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(problema_voo.errors.count, "error") %> prohibited this problema_voo from being saved:</h2>

      <ul>
        <% problema_voo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :situacao, style: "display: block" %>
    <%= form.text_field :situacao %>
  </div>

  <div>
    <%= form.label :detalhe, style: "display: block" %>
    <%= form.text_field :detalhe %>
  </div>

  <div>
    <%= form.label :usuario, style: "display: block" %>
    <%= form.text_field :usuario %>
  </div>

  <div>
    <%= form.label :endereço, style: "display: block" %>
    <%= form.text_field :endereço %>
  </div>

  <div>
    <%= form.label :provas, style: "display: block" %>
    <%= form.text_field :provas %>
  </div>

  <div>
    <%= form.label :advogado, style: "display: block" %>
    <%= form.text_field :advogado %>
  </div>
<br>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/problema_voos/_problema_voo.html.erb
<div id="<%= dom_id problema_voo %>">
  <p>
    <strong>Situacao:</strong>
    <%= problema_voo.situacao %>
  </p>

  <p>
    <strong>Detalhe:</strong>
    <%= problema_voo.detalhe %>
  </p>

  <p>
    <strong>Usuario:</strong>
    <%= problema_voo.usuario %>
  </p>

  <p>
    <strong>Endereço:</strong>
    <%= problema_voo.endereço %>
  </p>

  <p>
    <strong>Provas:</strong>
    <%= problema_voo.provas %>
  </p>

  <p>
    <strong>Advogado:</strong>
    <%= problema_voo.advogado %>
  </p>



</div>

app/views/problema_voos/edit.html.erb
<h1>Editing problema voo</h1>

<%= render "form", problema_voo: @problema_voo %>

<br>

<div>
  <%= link_to "Visualizar", @problema_voo %> |
  <%= link_to "Voltar para os problemas com voos", problema_voos_path %>
</div>

app/views/problema_voos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Problema voos</h1>

<div id="problema_voos">
  <% @problema_voos.each do |problema_voo| %>
    <%= render problema_voo %>
    <p>
      <%= link_to "Visualizar", problema_voo %>
    </p>
  <% end %>
</div>

<%= link_to "Adicionar nova ocorrência", new_problema_voo_path %><br><br>
<%= link_to "Voltar", root_path %>

app/views/problema_voos/new.html.erb
<h1>Cadastro de pedidos (voos)</h1>

<%= render "form", problema_voo: @problema_voo %>

<br>

<div>
  <%= link_to "Ir para os problemas com voos", problema_voos_path %><br><br>
  <%= link_to "Voltar para o menu", root_path %>
</div>

app/views/problema_voos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @problema_voo %>

<div>
  <%= link_to "Editar", edit_problema_voo_path(@problema_voo) %> |
  <%= link_to "Voltar para os problemas com voos", problema_voos_path %>
<br><br>
  <%= button_to "Apagar", @problema_voo, method: :delete %><br><br>
  <%= link_to "Voltar para o menu", root_path %>
</div>